version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /alerts
    schedule:
      interval: daily
      time: "03:00"
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /heartbeat
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /slack
    schedule:
      interval: daily
      time: "03:00"
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gha-all-dependencies:
        patterns:
          - "*"
    target-branch: main
    commit-message:
      prefix: BAU
