version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    cooldown:
      default-days: 7
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
      npm-eslint-dependencies:
        patterns:
          - "*eslint*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /alerts
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /heartbeat
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    directory: /slack
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    groups:
      npm-aws-dependencies:
        patterns:
          - "@aws-sdk/*"
    open-pull-requests-limit: 100
    target-branch: main
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
    open-pull-requests-limit: 10
    groups:
      gha-all-dependencies:
        patterns:
          - "*"
    target-branch: main
    commit-message:
      prefix: BAU
