repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: tflint
        name: Run tflint (terraform linter)
        files: ^ci/terraform/
        require_serial: true
        types_or:
          - hcl
          - terraform
        language: golang
        additional_dependencies:
          - github.com/terraform-linters/tflint@v0.55.0
        entry: scripts/tflint.py
        args:
          - --minimum-failure-severity=warning
          - --fix

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.19.0"
    hooks:
      - id: terraform-docs-go
        types_or:
          - hcl
          - terraform
        types: []
        files: ^ci/terraform/modules/
        args:
          - ci/terraform

  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint
        language: node
        types_or:
          - javascript
          - ts
        entry: yarn run eslint --fix
        pass_filenames: true
      - id: prettier
        name: Run prettier
        language: node
        types: [text]
        stages: [pre-commit]
        entry: prettier --write --ignore-unknown
        additional_dependencies: ["prettier@^3.4.2"]
        pass_filenames: true
        # ignore all readme files in the ci/terraform directory as they are generated by terraform-docs
        exclude: ^ci/terraform/.*/README.md$
      - id: shfmt
        name: shfmt (shell scripts)
        language: golang
        additional_dependencies:
          - mvdan.cc/sh/v3/cmd/shfmt@v3.10.0
        entry: shfmt
        types:
          - file
          - shell
        exclude_types:
          - zsh
        exclude: ^(dev-platform|docker|terraform|service-down-page-config)/.*$
        args:
          - -w # write
          - -s # simplify
          - -l # list files that differ

      - id: tfupdate-lock
        name: Update terraform provider locks
        files: "/versions.tf$"
        pass_filenames: false
        types:
          - file
        language: golang
        additional_dependencies:
          - github.com/minamijoyo/tfupdate@v0.8.5
        entry: tfupdate lock
        args:
          - --platform
          - linux_amd64
          - --platform
          - linux_arm64
          - --platform
          - darwin_amd64
          - --platform
          - darwin_arm64
          - --platform
          - windows_amd64
          - -r
          - ci/terraform

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

  - repo: https://github.com/lalten/check-gha-pinning
    rev: v1.3.0
    hooks:
      - id: check-gha-pinning

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
