version = 0.1
[dev.deploy.parameters]
stack_name = "smoke-test-canary"
resolve_s3 = false
s3_bucket = "smoke-test-pipeline-githubartifactsourcebucket-uog04vs8nxvj"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "VpcStackName=\"vpc\" Environment=\"dev\""
image_repositories = []
