sonar.projectKey=govuk-one-login_authentication-smoke-tests
sonar.organization=govuk-one-login
sonar.sources=./src,./alerts,./slack,./heartbeat
sonar.tests=./alerts/test,./slack/test,./heartbeat/test
sonar.exclusions=**/test/**
sonar.javascript.lcov.reportPaths=alerts/coverage/lcov.info,slack/coverage/lcov.info,heartbeat/coverage/lcov.info
