name: "Build SP: Build and deploy smoke tests"
# This workflow builds and deploys smoke tests for the authentication module.

on:
  push:
    branches:
      - main

jobs:
  pr-data:
    name: Get data for merged PR
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/call_get_pr_data.yml

  deploy:
    needs: pr-data
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up SAM cli
        uses: aws-actions/setup-sam@f664fad9e12492edfc187a31f575537dfbb0ff63 # v2
        with:
          use-installer: true
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20.17.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --production --frozen-lockfile

      - name: Build smoke tests
        run: yarn run build:all

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.GHA_BUILD_ROLE }}
          aws-region: eu-west-2

      - name: SAM build
        run: |
          sam validate --lint -t template.yaml
          sam build --parallel -t template.yaml

      - name: Deploy SAM app # synthetics-directory is used for synthetics canary Artifacts upload to S3
        uses: govuk-one-login/devplatform-upload-action@8851ef243c713dab19b860cca0edd741f9bde4e4 # PSREDEV-2607
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          template-file: .aws-sam/build/template.yaml
          synthetics-directory: ./dist
