name: Pre-merge checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Use Node.js 22.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22.22.2"
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Check formatting
        run: npm run check-pretty
      - name: Build app
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run alerts tests
        run: cd alerts && npm ci --ignore-scripts && npm run test:coverage
      - name: Run slack tests
        run: cd slack && npm ci --ignore-scripts && npm run test:coverage
      - name: Run heartbeat tests
        run: cd heartbeat && npm ci --ignore-scripts && npm run test:coverage

  run-sonar-code-analysis:
    name: Run SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Use Node.js 22.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22.22.2"
      - name: Run alerts tests with coverage
        run: cd alerts && npm ci --ignore-scripts && npm run test:coverage
      - name: Run slack tests with coverage
        run: cd slack && npm ci --ignore-scripts && npm run test:coverage
      - name: Run heartbeat tests with coverage
        run: cd heartbeat && npm ci --ignore-scripts && npm run test:coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
